/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-07-29 05:15:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _1_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("<!--<style>\r\n");
      out.write("	table{border:#FF9900 double }\r\n");
      out.write("	td{text-align:center;padding:5}\r\n");
      out.write("</style>-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style_daun.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	window.onload = function() {\r\n");
      out.write("		document.getElementById('Submit').onclick = check;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function check() {\r\n");
      out.write("		if (document.form.user_email.value == \"\") {\r\n");
      out.write("			alert(\"이메일을 입력하세요.\")\r\n");
      out.write("			document.form.user_email.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (document.form.user_password.value == \"\") {\r\n");
      out.write("			alert(\"비밀번호를 입력하세요.\")\r\n");
      out.write("			document.form.user_password.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		document.form.submit();//전송\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\">\r\n");
      out.write("<div class=\"login\">\r\n");
      out.write("    <form action=\"login_go.do\" method=\"post\" name=\"form\" method=\"post\" class=\"table2\">\r\n");
      out.write("	<!--<form name=\"form\" action=\"login.do\" method=\"post\">-->\r\n");
      out.write("<div class=\"register-logo\">\r\n");
      out.write("<a href=\"#\"><img src=\"resources/img/logo.png\" width=\"200px\"/></a>\r\n");
      out.write("</div>\r\n");
      out.write("	<div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_email\" type=\"text\" class=\"normal\" placeholder=\"이메일\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_password\" type=\"password\" class=\"normal\" placeholder=\"비밀번호\">\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    <div align=\"center\"> \r\n");
      out.write("        <input type=\"button\" name=\"Submit\" id=\"Submit\" class=\"confirm\"  value=\"로그인\">\r\n");
      out.write("  \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"daun-sub\">\r\n");
      out.write("       <a href=\"1_register.do\">회원가입</a>\r\n");
      out.write("    	<a href=\"#\">이메일/비밀번호 찾기</a>\r\n");
      out.write("    	<a href=\"1_login_admin.do\">관리자 로그인</a>\r\n");
      out.write("        </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
