/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-07-31 10:45:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class community_005fboard3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1627524339000L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1627517362000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1627573394313L));
    _jspx_dependants.put("jar:file:/C:/zzz/workspace/littlePick/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/littlePick/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>커뮤니티 - 건강</title>\r\n");
      out.write("<link rel=\"icon\" href=\"resources/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/linericon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style_0joo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ================ 게시판 상단 ================= -->\r\n");
      out.write("<!-- 헤더 인클루드 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--================ Start Header Menu Area =================-->\r\n");
      out.write("	<header class=\"header_area\">\r\n");
      out.write("		<div class=\"top_menu_container\">\r\n");
      out.write("			<ul class=\"top_menu_list\">\r\n");
      out.write("				<li class=\"top_menu_item\"><a class=\"top_menu_anchor\" href=\"mypage_board.do\">마이페이지</a></li>\r\n");
      out.write("				<li class=\"top_menu_item\"><a class=\"top_menu_anchor\" href=\"1_logout.do\">로그아웃</a></li>\r\n");
      out.write("				<li class=\"top_menu_item\"><a class=\"top_menu_anchor\" href=\"#\">고객센터</a>\r\n");
      out.write("				</li>		\r\n");
      out.write("			</ul>		\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"main_menu\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<div class=\"top_container\">\r\n");
      out.write("					<div class=\"logo_container\">\r\n");
      out.write("						<a class=\"navbar-brand logo_h\" href=\"index.jsp\"><img src=\"resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("						<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("							data-target=\"#navbarSupportedContent\"\r\n");
      out.write("							aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("							aria-label=\"Toggle navigation\">\r\n");
      out.write("							<span class=\"icon-bar\"></span> \r\n");
      out.write("							<span class=\"icon-bar\"></span> \r\n");
      out.write("							<span class=\"icon-bar\"></span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("						<ul class=\"nav navbar-nav menu_nav ml-auto mr-auto\">\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"category.do\" class=\"nav-link\" data-toggle=\"dropdown\"\r\n");
      out.write("								role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fas fa-bars\"></i> 전체 카테고리</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"productList.do?category_num=1\">신선식품 </a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"productList.do?category_num=2\">간편식</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"productList.do?category_num=3\">생필품 </a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"#\">신상품</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"#\">베스트</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"#\">특가/혜택</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"community.do\" data-toggle=\"dropdown\"\r\n");
      out.write("							aria-haspopup=\"true\" aria-expanded=\"false\">커뮤니티</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community.do\">전체 </a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board1.do\">요리 </a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board2.do\">생활</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board3.do\">건강</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board4.do\">번개팅</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"nav-shop\">\r\n");
      out.write("							<li class=\"nav-item\">\r\n");
      out.write("							<form action=\"productList.do\" method=\"get\">\r\n");
      out.write("							<input id=\"search_input_box\" name=\"product_name\" type=\"text\" placeholder=\"search\">\r\n");
      out.write("							<button type=\"submit\"><i class=\"ti-search\"></i></button>\r\n");
      out.write("							</form>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"nav-item\"><button><i class=\"fas fa-shipping-fast\"></i></button></li>\r\n");
      out.write("							<li class=\"nav-item\"><a href=\"cartList.do\"><button><i class=\"ti-shopping-cart\"></i><span class=\"nav-shop__circle\">3</span></button></a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<!-- <li class=\"nav-item\"><a class=\"button button-header\" href=\"#\">Buy Now</a></li> -->\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<!--================ End Header Menu Area =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- 게시판 명 -->\r\n");
      out.write("	<div class=\"board-title\">\r\n");
      out.write("		<h3>건강</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<!-- 글쓰기버튼 -->\r\n");
      out.write("	<div class=\"board-write\">\r\n");
      out.write("	<a class=\"button button-blog\" href=community_board_input.do>글쓰기</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<!-- 검색창 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"board-search\">\r\n");
      out.write("	<div class=\"blog_right_sidebar\">\r\n");
      out.write("		<div class=\"single_sidebar_widget search_widget\">\r\n");
      out.write("			<form action=\"community_search.do\" method=\"post\">\r\n");
      out.write("			<div class=\"input-group\">\r\n");
      out.write("			<select class=\"form-select\" name=\"searchCondition\">\r\n");
      out.write("				<option class=\"form-select\" value=\"content_title\">제목</option>\r\n");
      out.write("				<option value=\"content\">내용</option>\r\n");
      out.write("				<option value=\"user_nickname\">작성자</option>\r\n");
      out.write("			</select>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" name=\"searchKeyword\" placeholder=\"커뮤니티 글 검색하기\">\r\n");
      out.write("				<span class=\"input-group-btn\">\r\n");
      out.write("					<button class=\"btn btn-default\" type=\"submit\">\r\n");
      out.write("						<i class=\"lnr lnr-magnifier\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"single-sidebar-widget tag_cloud_widget\">\r\n");
      out.write("			<div class=\"br\"></div>\r\n");
      out.write("			<ul class=\"list\">\r\n");
      out.write("				<li><a href=\"community_search.do?searchCondition=content_title&searchKeyword=등산\"># 등산</a></li>\r\n");
      out.write("				<li><a href=\"community_search.do?searchCondition=content_title&searchKeyword=냉라면\"># 냉라면</a></li>\r\n");
      out.write("				<li><a href=\"community_search.do?searchCondition=content_title&searchKeyword=에어컨\"># 에어컨</a></li>\r\n");
      out.write("				<li><a href=\"community_search.do?searchCondition=content_title&searchKeyword=양파\"># 양파</a></li>\r\n");
      out.write("				<li><a href=\"community_search.do?searchCondition=content_title&searchKeyword=음식물\"># 음식물</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("	<!-- ================ 게시판 상단 끝 ================= -->\r\n");
      out.write("	\r\n");
      out.write(" <hr>\r\n");
      out.write("\r\n");
      out.write("  	<!--================건강 Area =================-->\r\n");
      out.write("  <section class=\"commu_area\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("		<div class=\"board-select\">\r\n");
      out.write("		<form action=\"community_board3.do\" method=\"post\">\r\n");
      out.write("        <select name=\"selectOrder\">\r\n");
      out.write("				<option value=\"b.content_num\">최신순</option>\r\n");
      out.write("				<option value=\"b.content_count\">조회순</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<input class=\"selectOrder_btn\" type=\"submit\" value=\"조회\" >\r\n");
      out.write("		</form>\r\n");
      out.write("    	<a></a>\r\n");
      out.write("    	</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("      </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("	\r\n");
      out.write("	<!--================건강 Area 끝 =================-->\r\n");
      out.write("	<!--================페이징 =================-->\r\n");
      out.write("	 \r\n");
      out.write("	<!-- <nav class=\"blog-pagination justify-content-center d-flex\">\r\n");
      out.write("		<ul class=\"pagination\">\r\n");
      out.write("			<li class=\"page-item\"><a href=\"#\" class=\"page-link\" aria-label=\"Previous\">\r\n");
      out.write("				<span aria-hidden=\"true\">\r\n");
      out.write("					<span class=\"lnr lnr-chevron-left\"></span>\r\n");
      out.write("				</span></a></li>\r\n");
      out.write("			<li class=\"page-item active\"><a href=\"#\" class=\"page-link\">01</a></li>\r\n");
      out.write("			<li class=\"page-item\"><a href=\"#\" class=\"page-link\">02</a></li>\r\n");
      out.write("			<li class=\"page-item\"><a href=\"#\" class=\"page-link\">03</a></li>\r\n");
      out.write("			<li class=\"page-item\"><a href=\"#\" class=\"page-link\">04</a></li>\r\n");
      out.write("			<li class=\"page-item\"><a href=\"#\" class=\"page-link\">05</a></li>\r\n");
      out.write("			<li class=\"page-item\"><a href=\"#\" class=\"page-link\"aria-label=\"Next\">\r\n");
      out.write("				<span aria-hidden=\"true\">\r\n");
      out.write("					<span class=\"lnr lnr-chevron-right\"></span>\r\n");
      out.write("				</span></a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav> -->\r\n");
      out.write(" 	<!--================페이징 끝 =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start footer Area  =================-->	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start footer Area  =================-->\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("		<div class=\"footer-area\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row section_gap\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title large_title\">Our Mission</h4>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing\r\n");
      out.write("								made fly you're no divided deep moved us lan Gathering thing us\r\n");
      out.write("								land years living.</p>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing\r\n");
      out.write("								made fly you're no divided deep moved</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Quick Links</h4>\r\n");
      out.write("							<ul class=\"list\">\r\n");
      out.write("								<li><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li><a href=\"#\">신상품</a></li>\r\n");
      out.write("								<li><a href=\"#\">베스트</a></li>\r\n");
      out.write("								<li><a href=\"#\">특가/혜택</a></li>\r\n");
      out.write("								<li><a href=\"#\">커뮤니티</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget instafeed\">\r\n");
      out.write("							<h4 class=\"footer_title\">고객센터</h4>\r\n");
      out.write("							<ul class=\"list instafeed d-flex flex-wrap\">\r\n");
      out.write("								<li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"#\">자주하는 질문</a></li>\r\n");
      out.write("								<li><a href=\"#\">1:1 문의하기</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Contact Us</h4>\r\n");
      out.write("						<div class=\"ml-40\">\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-location-arrow\"></span> Head Office\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>123, Main Street, Your City</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-phone\"></span> Phone Number\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									+123 456 7890 <br> +123 456 7890\r\n");
      out.write("								</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-envelope\"></span> Email\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									free@infoexample.com <br> www.infoexample.com\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-bottom\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row d-flex\">\r\n");
      out.write("					<p class=\"col-lg-12 footer-text text-center\">\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>\r\n");
      out.write("							document.write(new Date().getFullYear());\r\n");
      out.write("						</script>\r\n");
      out.write("						All rights reserved \r\n");
      out.write("						\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/vendors/mail-script.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/community_board3.jsp(90,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/community_board3.jsp(90,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("board");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("				<div class=\"col-sm-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
            out.write("					<div class=\"categories_post\">\r\n");
            out.write("						<a href=\"community_board_view.do?content_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <img\r\n");
            out.write("							src=\"resources/upload/board/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content_image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"350px\"\r\n");
            out.write("							height=\"350px\">\r\n");
            out.write("						</a>\r\n");
            out.write("						<div class=\"blog_info\">\r\n");
            out.write("							<a href=\"community_board_view.do?content_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("								<h5>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("							</a><br> <a><img\r\n");
            out.write("								src=\"resources/upload/user/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.user_image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"20px\" href=\"#\"></a><a href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.user_nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a><br>\r\n");
            out.write("							<a><i class=\"lnr lnr-calendar-full\"></i>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a> <a><i\r\n");
            out.write("								class=\"lnr lnr-eye\"></i>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content_count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>\r\n");
            out.write("				</div>\r\n");
            out.write("			\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
