/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-07-29 05:34:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1627524339000L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1627517362000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품 상세페이지</title>\r\n");
      out.write("<link rel=\"icon\" href=\"resources/img/Fevicon.png\" type=\"resources/image/png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/littlePick/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--================ Start Header Menu Area =================-->\r\n");
      out.write("	<header class=\"header_area\">\r\n");
      out.write("		<div class=\"top_menu_container\">\r\n");
      out.write("			<ul class=\"top_menu_list\">\r\n");
      out.write("				<li class=\"top_menu_item\"><a class=\"top_menu_anchor\" href=\"mypage_board.do\">마이페이지</a></li>\r\n");
      out.write("				<li class=\"top_menu_item\"><a class=\"top_menu_anchor\" href=\"1_logout.do\">로그아웃</a></li>\r\n");
      out.write("				<li class=\"top_menu_item\"><a class=\"top_menu_anchor\" href=\"#\">고객센터</a>\r\n");
      out.write("				</li>		\r\n");
      out.write("			</ul>		\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"main_menu\">\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("				<div class=\"top_container\">\r\n");
      out.write("					<div class=\"logo_container\">\r\n");
      out.write("						<a class=\"navbar-brand logo_h\" href=\"index.jsp\"><img src=\"resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("						<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("							data-target=\"#navbarSupportedContent\"\r\n");
      out.write("							aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("							aria-label=\"Toggle navigation\">\r\n");
      out.write("							<span class=\"icon-bar\"></span> \r\n");
      out.write("							<span class=\"icon-bar\"></span> \r\n");
      out.write("							<span class=\"icon-bar\"></span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("						<ul class=\"nav navbar-nav menu_nav ml-auto mr-auto\">\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a href=\"category.do\" class=\"nav-link\" data-toggle=\"dropdown\"\r\n");
      out.write("								role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fas fa-bars\"></i> 전체 카테고리</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"productList.do?category_num=1\">신선식품 </a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"productList.do?category_num=2\">간편식</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"productList.do?category_num=3\">생필품 </a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"#\">신상품</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"#\">베스트</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"#\">특가/혜택</a></li>\r\n");
      out.write("							<li class=\"nav-item submenu dropdown\"><a class=\"nav-link\" href=\"community.do\" data-toggle=\"dropdown\"\r\n");
      out.write("							aria-haspopup=\"true\" aria-expanded=\"false\">커뮤니티</a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community.do\">전체 </a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board1.do\">요리 </a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board2.do\">생활</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board3.do\">건강</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"nav-link\" href=\"community_board4.do\">번개팅</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"nav-shop\">\r\n");
      out.write("							<li class=\"nav-item\">\r\n");
      out.write("							<form action=\"productList.do\" method=\"get\">\r\n");
      out.write("							<input id=\"search_input_box\" name=\"product_name\" type=\"text\" placeholder=\"search\">\r\n");
      out.write("							<button type=\"submit\"><i class=\"ti-search\"></i></button>\r\n");
      out.write("							</form>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"nav-item\"><button><i class=\"fas fa-shipping-fast\"></i></button></li>\r\n");
      out.write("							<li class=\"nav-item\"><a href=\"cartList.do\"><button><i class=\"ti-shopping-cart\"></i><span class=\"nav-shop__circle\">3</span></button></a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<!-- <li class=\"nav-item\"><a class=\"button button-header\" href=\"#\">Buy Now</a></li> -->\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<!--================ End Header Menu Area =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"/littlePick/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ================ start banner area ================= -->	\r\n");
      out.write("<!-- 	<section class=\"blog-banner-area\" id=\"category\">\r\n");
      out.write("		<div class=\"container product-banner\">\r\n");
      out.write("			<div class=\"product-banner\">\r\n");
      out.write("				<div class=\"text-category\">\r\n");
      out.write("					<h5>상품</h5>\r\n");
      out.write("					<nav aria-label=\"breadcrumb\" class=\"banner-breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\" aria-current=\"page\">상품 상세</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("    </div>\r\n");
      out.write("	</section> -->\r\n");
      out.write("	<!-- ================ end banner area ================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--================Single Product Area =================-->\r\n");
      out.write("	<div class=\"product_image_area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row s_product_inner\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"owl-carousel owl-theme s_Product_carousel\">\r\n");
      out.write("						<div class=\"single-prd-item\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"resources/img/product/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- <div class=\"single-prd-item\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"img/category/s-p1.jpg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"single-prd-item\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"img/category/s-p1.jpg\" alt=\"\">\r\n");
      out.write("						</div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-5 offset-lg-1\">\r\n");
      out.write("					<div class=\"s_product_text\">\r\n");
      out.write("					<form id=\"cart-int\"action=\"cartInsert.do\" method=\"get\">\r\n");
      out.write("						<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>	\r\n");
      out.write("						<br/>\r\n");
      out.write("						<h2><span id=\"price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.sale_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>원</h2>\r\n");
      out.write("						<br/>\r\n");
      out.write("						<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_info }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("						<div class=\"product_count\">\r\n");
      out.write("							\r\n");
      out.write("		              		<label for=\"qty\"><h5>수량:</h5></label>    \r\n");
      out.write("							<button onclick=\"var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;\"\r\n");
      out.write("		               				class=\"reduced items-count\" type=\"button\"><i class=\"far fa-minus-square\"></i></button>\r\n");
      out.write("		               		<input type=\"hidden\" name=\"product_num\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("		               		<input type=\"text\" name=\"product_count\" id=\"sst\" size=\"2\" maxlength=\"12\" value=\"1\" title=\"Quantity:\" class=\"input-text qty\">\r\n");
      out.write("		               		<button onclick=\"var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;\"\r\n");
      out.write("									class=\"increase items-count\" type=\"button\"><i class=\"far fa-plus-square\"></i></button>\r\n");
      out.write("							\r\n");
      out.write("		               		<br/><br/>          \r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_total_area\">\r\n");
      out.write("						<div><label><h5>총 상품 금액:&nbsp;&nbsp;</h5></label><label><h2><span id=\"product_total\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.sale_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>원</h2></label><br/></div>\r\n");
      out.write("						<div><h5>로그인 후, 회원할인가와 적립혜택 제공</h5></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"stock_cart_area\">\r\n");
      out.write("						<a class=\"button stock-alarm-btn\" href=\"#\">재고알림</a><a class=\"button primary-btn\" onclick=\"document.getElementById('cart-int').submit();\">장바구니 담기</a>     \r\n");
      out.write("						</div>\r\n");
      out.write("<!-- 					<div class=\"card_area d-flex align-items-center\">\r\n");
      out.write("							<a class=\"icon_btn\" href=\"#\"><i class=\"lnr lnr lnr-diamond\"></i></a>\r\n");
      out.write("							<a class=\"icon_btn\" href=\"#\"><i class=\"lnr lnr lnr-heart\"></i></a>\r\n");
      out.write("						</div> \r\n");
      out.write("-->					\r\n");
      out.write("					</form>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--================End Single Product Area =================-->\r\n");
      out.write("\r\n");
      out.write("	<!--================Product Description Area =================-->\r\n");
      out.write("	<section class=\"product_description_area\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<ul class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" id=\"home-tab\" data-toggle=\"tab\" href=\"#home\" role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">상품설명</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\" aria-controls=\"profile\" aria-selected=\"false\">상세정보</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link active\" id=\"review-tab\" data-toggle=\"tab\" href=\"#review\" role=\"tab\" aria-controls=\"review\" aria-selected=\"false\">리뷰</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a class=\"nav-link\" id=\"contact-tab\" data-toggle=\"tab\" href=\"#contact\" role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">문의</a>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("					<p>Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes\r\n");
      out.write("						and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in\r\n");
      out.write("						Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to\r\n");
      out.write("						London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an\r\n");
      out.write("						officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a\r\n");
      out.write("						job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when\r\n");
      out.write("						showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a\r\n");
      out.write("						child’s painting set for her birthday and it was with this that she produced her first significant work, a\r\n");
      out.write("						half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly\r\n");
      out.write("						named ‘Hangover’ by Beryl’s husband and</p>\r\n");
      out.write("					<p>It is often frustrating to attempt to plan meals that are designed for one. Despite this fact, we are seeing\r\n");
      out.write("						more and more recipe books and Internet websites that are dedicated to the act of cooking for one. Divorce and\r\n");
      out.write("						the death of spouses or grown children leaving for college are all reasons that someone accustomed to cooking for\r\n");
      out.write("						more than one would suddenly need to learn how to adjust all the cooking practices utilized before into a\r\n");
      out.write("						streamlined plan of cooking that is more efficient for one person creating less</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Width</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>128mm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Height</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>508mm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Depth</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>85mm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Weight</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>52gm</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Quality checking</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>yes</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Freshness Duration</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>03days</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>When packeting</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Without touch of hand</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>Each Box contains</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<h5>60pcs</h5>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade\" id=\"contact\" role=\"tabpanel\" aria-labelledby=\"contact-tab\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"comment_list\">\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-1.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<h5>12th Feb, 2018 at 05:56 pm</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">Reply</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item reply\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-2.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<h5>12th Feb, 2018 at 05:56 pm</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">Reply</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"img/product/review-3.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<h5>12th Feb, 2018 at 05:56 pm</h5>\r\n");
      out.write("											<a class=\"reply_btn\" href=\"#\">Reply</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"review_box\">\r\n");
      out.write("								<h4>Post a comment</h4>\r\n");
      out.write("								<form class=\"row contact_form\" action=\"contact_process.php\" method=\"post\" id=\"contactForm\" novalidate=\"novalidate\">\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"Your Full name\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email Address\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" id=\"number\" name=\"number\" placeholder=\"Phone Number\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<textarea class=\"form-control\" name=\"message\" id=\"message\" rows=\"1\" placeholder=\"Message\"></textarea>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-12 text-right\">\r\n");
      out.write("										<button type=\"submit\" value=\"submit\" class=\"btn primary-btn\">Submit Now</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tab-pane fade show active\" id=\"review\" role=\"tabpanel\" aria-labelledby=\"review-tab\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"row total_rate\">\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<div class=\"box_total\">\r\n");
      out.write("										<h5>Overall</h5>\r\n");
      out.write("										<h4>4.0</h4>\r\n");
      out.write("										<h6>(03 Reviews)</h6>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<div class=\"rating_list\">\r\n");
      out.write("										<h3>Based on 3 Reviews</h3>\r\n");
      out.write("										<ul class=\"list\">\r\n");
      out.write("											<li><a href=\"#\">5 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">4 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">3 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">2 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("											<li><a href=\"#\">1 Star <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i\r\n");
      out.write("													 class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i> 01</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"review_list\">\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"resources/img/product/review-1.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"resources/img/product/review-2.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"review_item\">\r\n");
      out.write("									<div class=\"media\">\r\n");
      out.write("										<div class=\"d-flex\">\r\n");
      out.write("											<img src=\"resources/img/product/review-3.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"media-body\">\r\n");
      out.write("											<h4>Blake Ruiz</h4>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("											<i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\r\n");
      out.write("										commodo</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"review_box\">\r\n");
      out.write("								<h4>Add a Review</h4>\r\n");
      out.write("								<p>Your Rating:</p>\r\n");
      out.write("								<ul class=\"list\">\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("									<li><a href=\"#\"><i class=\"fa fa-star\"></i></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p>Outstanding</p>\r\n");
      out.write("                <form action=\"#/\" class=\"form-contact form-review mt-3\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"name\" type=\"text\" placeholder=\"Enter your name\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"email\" type=\"email\" placeholder=\"Enter email address\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"subject\" type=\"text\" placeholder=\"Enter Subject\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <textarea class=\"form-control different-control w-100\" name=\"textarea\" id=\"textarea\" cols=\"30\" rows=\"5\" placeholder=\"Enter Message\"></textarea>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group text-center text-md-right mt-3\">\r\n");
      out.write("                    <button type=\"submit\" class=\"button button--active button-review\">Submit Now</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--================End Product Description Area =================-->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/nice-select/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!--================ Start footer Area  =================-->\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("		<div class=\"footer-area\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row section_gap\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title large_title\">Our Mission</h4>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing\r\n");
      out.write("								made fly you're no divided deep moved us lan Gathering thing us\r\n");
      out.write("								land years living.</p>\r\n");
      out.write("							<p>So seed seed green that winged cattle in. Gathering thing\r\n");
      out.write("								made fly you're no divided deep moved</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Quick Links</h4>\r\n");
      out.write("							<ul class=\"list\">\r\n");
      out.write("								<li><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li><a href=\"#\">신상품</a></li>\r\n");
      out.write("								<li><a href=\"#\">베스트</a></li>\r\n");
      out.write("								<li><a href=\"#\">특가/혜택</a></li>\r\n");
      out.write("								<li><a href=\"#\">커뮤니티</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget instafeed\">\r\n");
      out.write("							<h4 class=\"footer_title\">고객센터</h4>\r\n");
      out.write("							<ul class=\"list instafeed d-flex flex-wrap\">\r\n");
      out.write("								<li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"#\">자주하는 질문</a></li>\r\n");
      out.write("								<li><a href=\"#\">1:1 문의하기</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"offset-lg-1 col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("						<div class=\"single-footer-widget tp_widgets\">\r\n");
      out.write("							<h4 class=\"footer_title\">Contact Us</h4>\r\n");
      out.write("						<div class=\"ml-40\">\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-location-arrow\"></span> Head Office\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>123, Main Street, Your City</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-phone\"></span> Phone Number\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									+123 456 7890 <br> +123 456 7890\r\n");
      out.write("								</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"sm-head\">\r\n");
      out.write("									<span class=\"fa fa-envelope\"></span> Email\r\n");
      out.write("								</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									free@infoexample.com <br> www.infoexample.com\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-bottom\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row d-flex\">\r\n");
      out.write("					<p class=\"col-lg-12 footer-text text-center\">\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>\r\n");
      out.write("							document.write(new Date().getFullYear());\r\n");
      out.write("						</script>\r\n");
      out.write("						All rights reserved \r\n");
      out.write("						\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"resources/vendors/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/bootstrap/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/skrollr.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/nice-select/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/vendors/mail-script.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/product.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
